konflux-workspaces/workspaces

LICENSE, OWNERS
=> Add LICENSE and OWNERS files

e2e/pkg/context/host.go, e2e/step/workspace/workspace_then.go, server/core/context/context.go, server/core/workspace/workspace_update.go, server/core/workspace/worspace_list.go, server/core/workspace/worspace_read.go, server/main.go, server/persistence/cache/cache.go, server/persistence/kube/kube.go, server/rest/middleware/auth/jwt.go, server/rest/server.go
- Fix linters complaints on server
- Fix linters complaints on e2e
=> Fix linter complaints

operator/.golangci.yaml, operator/Makefile, server/.golangci.yaml, server/Makefile, server/main.go, server/rest/server.go
=> add golangci config and fix complaints

.github/workflows/security.yaml
=> add GitHub Action for security checks

operator/config/rbac/role.yaml
=> update operator's rbac/role manifest

.github/workflows/ci.yaml, server/.gitignore
Run unit tests and linting if anything under server/ has been modified.
=> Add CI for server

server/Dockerfile
=> fix(server): add log pkg to dockerfile

server/manifests/network/route.yaml, server/manifests/network/service.yaml, server/manifests/server/deployment.yaml, server/manifests/server/kustomization.yaml, server/manifests/server/proxy-config/dynamic.yaml, server/manifests/server/proxy-config/traefik.yaml
=> add proxy sidecar with metrics enabled

hack/install_toolchain.sh
=> update install_toolchain.sh script

.github/workflows/security.yaml, server/.golangci.yaml
=> exclude gosec G601

.github/workflows/push.yaml
=> fix push action

hack/.shellcheckrc
=> add shellcheckrc

.github/workflows/push.yaml
Use string equality operators, not integer equality operators.
=> fix image tags in release builds

.github/workflows/push.yaml, hack/demo.sh, hack/toolchain_build_push.sh, hack/toolchain_build_push_host.sh, hack/toolchain_build_push_member.sh, hack/workspaces_install.sh
- **update toolchain_build_push.sh script**
- **update GitHub Action**
=> ci image push

e2e/go.mod, operator/go.mod, server/go.mod
=> bump go to 1.22.2

operator/api/v1alpha1/workspace_types.go, server/persistence/mapper/internalworkspace_to_workspace.go, server/persistence/mapper/internalworkspace_to_workspace_test.go, server/persistence/mapper/internalworkspacelist_to_workspacelist.go, server/persistence/mapper/mapper.go, server/persistence/mapper/mapper_suite_test.go, server/persistence/mapper/workspace_to_internalworkspace.go, server/persistence/mapper/workspace_to_internalworkspace_test.go, server/persistence/mapper/workspacelist_to_internalworkspacelist.go
=> rest: add mapper package

operator/api/v1alpha1/workspace_types.go, server/persistence/internal/cache/cache.go, server/persistence/iwclient/iwclient.go, server/persistence/iwclient/iwclient_list.go, server/persistence/iwclient/iwclient_list_test.go, server/persistence/iwclient/iwclient_read.go, server/persistence/iwclient/iwclient_read_test.go, server/persistence/iwclient/iwclient_suite_test.go, server/persistence/iwclient/iwclient_test.go
=> rest: add iwclient package

e2e/hook/dump.go, e2e/hook/hook.go, e2e/pkg/dump/dump.go, e2e/step/step.go
=> e2e: add dump hook

server/core/workspace/v2/interfaces_write.go, server/persistence/writeclient/writeclient.go, server/persistence/writeclient/writeclient_create.go, server/persistence/writeclient/writeclient_create_test.go, server/persistence/writeclient/writeclient_suite_test.go, server/persistence/writeclient/writeclient_update.go, server/persistence/writeclient/writeclient_update_test.go
=> rest: add persistence/writeclient

e2e/pkg/cli/cli.go
=> e2e: enhance support for GenerateName in cli

e2e/go.mod, e2e/hook/host_client.go
=> e2e: add rest api

operator/controllers/usersignup_controller.go
=> op: add workspace display name label

e2e/go.mod, e2e/go.sum
=> e2e: update go mod

server/go.mod
=> rest: tidy go.mod

e2e/Makefile, e2e/hook/config.go, e2e/hook/host_client.go, e2e/hook/internal/config.go, e2e/hook/kubeconfig.go
=> e2e: allow disabling tls certificate validation

e2e/hook/namespace.go
=> e2e: use cmp.Or in hook/namespace

server/core/workspace/workspace_update.go
=> fix typo in core/workspaceupdater

e2e/hook/host_client.go, e2e/hook/kubeconfig.go, e2e/pkg/rest/client.go, e2e/pkg/rest/config.go, e2e/step/user/user_when.go
=> e2e: add rest client pkg

e2e/pkg/context/host.go
=> e2e: add UserWorkspace in pkg/context

operator/api/v1alpha1/workspace_types.go
=> add const DisplayNameDefaultWorkspace

e2e/step/workspace/workspace_then.go, operator/api/v1alpha1/workspace_types.go, operator/controllers/workspace_controller.go
=> api: add PublicViewerName const

server/persistence/writeclient/writeclient.go
=> rest: add writeclient's NewWithConfig

operator/controllers/workspace_controller.go, operator/main.go
=> op: watch spacebindings

ci/toolchain_manager.sh, hack/toolchain_install.sh, operator/api/v1alpha1/workspace_types.go
=> use latest toolchain proxy changes

e2e/pkg/dump/dump.go
=> e2e: reduce dump verbosity

e2e/step/user/user_common.go, server/config/rbac/clusterrole_usersignup_reader.yaml, server/config/rbac/clusterrolebinding_usersignup_reader.yaml, server/config/rbac/kustomization.yaml, server/core/context/context.go, server/core/workspace/workspace_create.go, server/core/workspace/workspace_create_test.go, server/core/workspace/workspace_list.go, server/core/workspace/workspace_read.go, server/core/workspace/workspace_update.go, server/main.go, server/persistence/internal/cache/cache.go, server/persistence/iwclient/iwclient_read.go, server/rest/middleware/usersignup.go, server/rest/server.go
Authentication is performed by checking the existence of a valid UserSignup.
UserSignup matching is performed on the JWT's `sub` field.
=> rest: use UserSignup in request authentication

operator/controllers/internalworkspace_controller.go, operator/internal/controller/internalworkspace_controller.go
=> op: remove kube RBAC

operator/internal/controller/internalworkspace_controller.go
- **op: remove kube RBAC**
- **op: Home InternalWorkspace is owned by UserSignup**
=> op: disable space creation and deletion

e2e/pkg/context/host.go
=> e2e: fix scenarioId hook

e2e/go.mod, e2e/go.sum, operator/go.mod, operator/go.sum, server/go.mod, server/go.sum
=> bump controller-runtime from v0.18.3 to v0.18.4

server/go.mod
=> rest: tidy go mod

.github/workflows/pages.yaml
=> fix pages upload

.github/workflows/pages.yaml
=> fix build book for GitHub Pages

Makefile
=> doc: remove tty requirement when building the book

doc/book/src/development/operator.md, doc/book/src/development/rest-api.md
=> doc: fix typos

server/rest/middleware/header_info.go, server/rest/middleware/header_info_test.go
=> rest: add unit tests for HeaderInfo Middleware

server/persistence/mapper/internalworkspace_to_workspace_test.go, server/persistence/mapper/internalworkspacelist_to_workspacelist.go, server/persistence/mapper/internalworkspacelist_to_workspacelist_test.go, server/persistence/mapper/workspace_to_internalworkspace_test.go, server/persistence/mapper/workspacelist_to_internalworkspacelist.go, server/persistence/mapper/workspacelist_to_internalworkspacelist_test.go
=> rest: add tests and bugfix for mapper pkg

operator/Dockerfile, server/Dockerfile, server/hack/deploy.sh
=> minor fixes

ci/toolchain_manager.sh
=> update kubesaw dependency

operator/Makefile, operator/cmd/main.go, operator/internal/controller/internalworkspace/internalworkspace_controller.go, operator/internal/controller/internalworkspace/internalworkspace_controller_test.go
That's a first set of tests for the InternalWorkspaces controller
=> op: add unit tests for InternalWorkspace controller

doc/book/src/operator/crds.md, doc/book/src/rest-api/crds.md, doc/book/src/rest-api/endpoints.md, e2e/Makefile, operator/api/v1alpha1/groupversion_info.go, operator/api/v1alpha1/internalworkspace_types.go, operator/config/crd/bases/workspaces.konflux-ci.dev_internalworkspaces.yaml, operator/config/crd/kustomization.yaml, operator/config/rbac/internalworkspace_editor_role.yaml, operator/config/rbac/internalworkspace_viewer_role.yaml, operator/config/rbac/role.yaml, operator/internal/controller/internalworkspace/internalworkspace_controller.go, operator/internal/controller/usersignup/usersignup_controller.go, server/api/v1alpha1/groupversion_info.go, server/config/crd/bases/workspaces.konflux-ci.dev_workspaces.yaml, server/config/crd/kustomization.yaml, server/config/rbac/role_workspace_server_editor.yaml, server/config/server/proxy-config/dynamic/config.yaml, server/rest/server.go
=> rename CRDs group to konflux-ci.dev

operator/internal/controller/usersignup/usersignup_controller.go, operator/internal/controller/usersignup/usersignup_controller_test.go, operator/internal/controller/usersignup/usersignup_suite_test.go
=> add fix and unit tests for UserSignupReconciler

operator/internal/controller/internalworkspace/internalworkspace_controller_test.go
=> enhance InternalWorkspace Reconciler's tests

Makefile, e2e/Makefile, operator/Makefile, server/Makefile
=> add make tidy

.github/dependabot.yml
=> simplify dependabot configuration

e2e/features/restapi/read.feature, e2e/features/workspaces.feature, e2e/pkg/auth/auth.go, e2e/pkg/rest/client.go, e2e/step/user/user.go, e2e/step/user/user_common.go, e2e/step/user/user_given.go, e2e/step/user/user_then.go, e2e/step/user/user_when.go, server/rest/workspace/read.go
This PR adds a test case for checking the behavior of the system when an user with a long name (>20 characters) onboards
=> add test case for user with long name

server/persistence/mapper/internalworkspace_to_workspace.go, server/persistence/mapper/internalworkspace_to_workspace_test.go
=> rest: set creationTimestamp in Workspaces

server/config/server/proxy-config/traefik.yaml
=> bump traefik jwt plugin

e2e/pkg/auth/auth.go, server/config/server/proxy-config/dynamic/config.yaml
=> rest: validate JWT's sub and exp

doc/book/src/operator/crds.md, doc/book/src/rest-api/crds.md
=> doc: add targetCluster to CRDs
