.github/workflows/ci.yaml
Run `shellcheck` in differential mode, which subtracts shellcheck warnings already in `main` from the PR branch.  This doesn't pick up on existing issues, but it'll catch stuff going forward.
=> add differential shellcheck to CI

.github/workflows/ci.yaml, .github/workflows/security.yaml
We should run this as a part of security checks, not as a part of CI for `server/` changes.
=> fix shellcheck CI configuration

.github/workflows/push.yaml
Push built artifacts to quay.io for further distribution, either for testing or use in production.
Containers are tagged under the following naming convention:
- Release artifacts are tagged with the first 8 characters of the latest commit.  The most-recently-pushed container will also be tagged with `latest`.
- Testing artifacts are tagged as `pr-${PR_NUMBER}-${COMMIT}`, where $PR_NUMBER is the pull request number, and $COMMIT is the first 8 characters on the latest commit.  This naming convention distinguishes testing artifacts from release artifacts.
=> cd: build/push images

.github/workflows/security.yaml, .gitignore, hack/demo.sh, hack/install_toolchain.sh, hack/install_workspaces.sh, server/hack/deploy.sh
Differential shellcheck was ignoring errors in some cases, which was causing shellcheck warnings not to be picked up.  Move away from it and use [shellcheck-sarif][1] as a SARIF provider.
[1]: https://docs.rs/crate/shellcheck-sarif/latest
=> ci: move away from differential shellcheck

.github/workflows/push.yaml, hack/toolchain_install.sh
We don't need them during release builds (i.e. a push to main), but they are needed as a part of ci.
=> Build kubesaw components as a part of ci

.github/workflows/push.yaml
In pull_request_target events, `$GITHUB_SHA` points to the base commit on `main`, not the latest commit on the PR branch.  Fix this.
=> use commit sha from PR head

.github/workflows/clean-images.yaml
We should remove stale testing images if the associated PR closes.  This will help spare us some repository clutter.
=> Remove testing images from quay on PR closure

ci/toolchain_manager.sh
See [here][1] for context.
[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/50802/rehearse-50802-pull-ci-konflux-workspaces-workspaces-main-e2e/1786059626001731584
=> use correct branch in deployment

.github/workflows/ci.yaml
Currently, the server/ CI workflow only runs if a PR has changes in the server/ directory.  This misses running some tools like linting when they get updated (for instance, see [PR #107][1]).  Run them when changes affect hack/tools/** and .github/** as well.
[1]: https://github.com/konflux-workspaces/workspaces/pull/107/checks?sha=5ef9206bc7d5bb502d8f095602fc15035fbb3a65
=> run server CI when dependencies change

e2e/go.mod, e2e/go.sum
Fixes a tidy error when trying to run e2e tests, see [here][1] for an example.
This was probably going to get picked up by dependabot, but it's causing us issues in openshift-ci.
[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/50802/rehearse-50802-pull-ci-konflux-workspaces-workspaces-main-e2e/1788314158404472832#1:build-log.txt%3A833
=> bump controller-runtime to v0.18.2 in e2e/

e2e/pkg/auth/auth.go
We have two error cases here:
- The decoded data is not valid.
- The x509 certificate doesn't contain an RSA private key (for instance, it could be an ECDSA or an ed25519 key).
Handle both of these cases and report the error, rather than panic when we eventually run into an issue.
=> e2e: check parse results of RSA private key

server/main.go
controller-runtime expects a logger to be setup using the `logr` package and registered using the `log.SetLogger` method.  Without this, controller-runtime refuses to propogate logging and causes issues.
=> enable logging in controller-runtime

e2e/Makefile, operator/Makefile, server/Makefile
This allows the build system to use alternative container runtimes for building containers, such as podman.  Behavior can be set using the `IMAGE_BUILDER` parameter/env var.
=> allow setting alternative image builders

e2e/hook/host_client.go, e2e/hook/kubeconfig.go
client-go does the right thing in more circumstances than we do.  On clusters, it should pick up credentials according to the secrets projected into the pod, while on desktop clients, it should respect `KUBECONFIG` env vars (defaulting to `~/.kube/config`).
This is a copy of what toolchain-e2e does during test initialization. See [init.go] and [kube_client.go] for more details.
[init.go]: https://github.com/codeready-toolchain/toolchain-e2e/blob/master/testsupport/init.go#L65-L74
[kube_client.go]: https://github.com/codeready-toolchain/toolchain-e2e/blob/master/testsupport/util/kube_client.go#L13-L20
=> e2e: use client-go's kubeconfig loaders

e2e/pkg/context/host.go, e2e/step/user/user_then.go, e2e/step/user/user_when.go, e2e/step/workspace/workspace_common.go, e2e/step/workspace/workspace_given.go, e2e/step/workspace/workspace_then.go, e2e/step/workspace/workspace_when.go
=> e2e: update context pkg

.github/workflows/ci.yaml
If we want to make the unit-testing job always pass before we can merge a PR, we need to have it run in almost all circumstances. With this change, all PRs will have unit tests run, not just when relevant paths have changed.
This also sets up unit testing for operator/ and fixes a bug where we were running the latest version of golang-ci instead of the pinned version.
=> ci: run more tests more often

e2e/pkg/rest/client.go
This was causing test failures, since the workspace client wasn't informed of how to deal with internal workspaces.  This should be safe to revert once #126 is merged.
=> e2e: add internal workspaces schema to workspaces client

e2e/Makefile
We may need to override the proxy url in the cluster in a way that the current method (fetching from the route's host) doesn't support.
=> e2e: allow overrides of PROXY_URL

e2e/Makefile, server/config/network/route.yaml
This fixes two related issues:
- The route wasn't terminating TLS connections properly, so any https connection to the rest api would fail.
- `PROXY_URL` wasn't setting a protocol, which was causing our client to default to http connections.
With these changes, the rest-api server should be properly setup to handle incoming https connections.
I believe this is what was causing openshift-ci tests to fail, though I'm not 100% certain.  I was able to reproduce similar behavior to the failures I was seeing over there by applying only the second commit (525dcc2).
=> Use https for workspace clients

e2e/step/workspace/workspace_when.go
Hooks relies on the context to be returned here.
Returning `nil` here breaks After hooks.
=> e2e: fix ctx return in workspace_when

.github/workflows/push.yaml
I wish github had a way of linting our workflow definitions so we didn't have to play golf with them, but until then, this is what we have to do.
=> fix typo in actions

operator/Makefile, server/Makefile
Context: https://github.com/konflux-workspaces/workspaces/actions/runs/9553798236/job/26333553977
=> release: use OUTDIR for tarball manifest paths

operator/Makefile
also fixes an issue with the `package` target not writing tarballs correctly
=> operator: add clean target

operator/Makefile
If operator/out doesn't exist, then the call to realpath to determine the location of the manifest tarball will fail, since realpath doesn't chain together paths if any higher-level directory doesn't exist.  To work around this, we reuse ROOT_DIR detection from server.
=> operator: fix OUTDIR path generation

e2e/Makefile
Since 000d58a (PR #174), operator/ hasn't respected the `IMAGE_BUILDER` env var, instead using `CONTAINER_TOOL`.  This means users trying to build with alternative image builders need to set two environment variables, not one.  This impacts e2e builds of images, where the assumption was that the `IMAGE_BUILDER` environment variable would control both operator and server.
To remedy this, have e2e infrastructure set `CONTAINER_TOOL` and `IMAGE_BUILDER` explicitly when invoking builds of each component.
=> e2e: set container tool env vars explicitly

operator/api/v1alpha1/internalworkspace_types.go, operator/config/crd/bases/workspaces.konflux.io_internalworkspaces.yaml, server/api/v1alpha1/workspace_types.go, server/config/crd/bases/workspaces.konflux.io_workspaces.yaml
Visibility field is only allowed to have value `community` or `private`.
This change enforces manifest validation on the visibility field for both InternalWorkspace and Workspace.
=> add CRD validation for visibility

e2e/Makefile
In some circumstances, we may want to deploy and run e2e tests in a namespace that isn't "workspaces-system".  This wires up the necessary infrastructure into e2e to do so.
=> e2e: allow overriding deployment/testing namespace

doc/book/src/operator/workflows.md
=> book: fix typos

server/persistence/readclient/readclient_list.go, server/persistence/readclient/readclient_list_test.go, server/persistence/readclient/readclient_read_test.go
=> rest: add tests for read and list in readclient pkg

server/log/log.go, server/log/log_suite_test.go, server/log/log_test.go, server/log/noophandler_test.go
=> rest: add unit tests for the log package

e2e/go.mod, e2e/go.sum, operator/go.mod, operator/go.sum, server/go.mod, server/go.sum
Upgrade the following packages:
- ginkgo to v2.19.1
- gomega to v1.34.0
Supercedes #246, #247, #248, and #250.
=> upgrade testing dependencies

server/config/default/kustomization.yaml, server/config/server/route.yaml
We had to make some changes to how RBAC works downstream on infra-deployments.  Backport these changes upstream to make releases easier.
=> backport changes from downstream

Makefile, operator/Makefile, server/Makefile
<details>
<summary><code>make [help]</code></summary>
```
Usage:
make <target>
General
help             Display this help.
Book
book             Build the book.
lint-book-sync   Synchronize book's linter vocabularies.
lint-book        Lint the book.
Development
vet              run go vet on all projects. Failures are ignored.
unit-test        run go test on all projects.
```
</details>
<details>
<summary><code>make -C server [help]</code></summary>
```
Usage:
make <target>
General
help             Display this help.
Development
manifests        Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
generate         Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
generate-code    Run go generate on the project.
clean …
```
=> makefiles default to help, enriched help output

.github/dependabot.yml
Both of these usually need to be keep in sync across our entire repository due to testing needs.
=> dependabot: add group for ginkgo & gomega

ci/toolchain_manager.sh
See these PRs for context:
- https://github.com/codeready-toolchain/toolchain-e2e/pull/1034
- https://github.com/codeready-toolchain/toolchain-e2e/pull/1041
- https://github.com/redhat-appstudio/infra-deployments/pull/4324
This is needed if we want to use `ci/toolchain-manager.sh` outside of CI environments.
=> ci: use latest ksctl during kubesaw deployment

hack/smoke.sh
To run these tests, you'll need to obtain a token corresponding to the environment you're wanting to test.  Tokens are not portable, i.e. a token from staging-external won't work for production-external.
Internal environments are not yet supported, since the PR for enabling them has not yet landed.  See [#4225] for details.
[#4225]: https://github.com/redhat-appstudio/infra-deployments/pull/4225
=> tests: add script for smoke testing

hack/smoke.sh
This changes the following:
- removes a false dependency on `mktemp`
- prints a message when tests pass
- passes data to jq in a way it can understand
=> smoke: some simple fixes

hack/smoke.sh
We were writing the log file to "${RESPONSE}", not "${LOG_FILE}", which made for invalid file names.
=> smoke: fix writing log file

.github/dependabot.yml
This change wants to force the update of `e2e`'s indirect dependencies related to ginkgo and gomega when they are updated in `operator`.
Look at #282 and #283 for examples of the problem. When gomega or ginkgo are updated in `operator`, they are not updated in `e2e` as they are indirect dependencies. As a consequence the build fails due to untidied gomod.
Alternatively, we can add ginkgo and gomega as `e2e`'s direct dependencies. I think it would be good to start using gomega `e2e`, but I don't see space for ginkgo at the moment.
=> add workspaces/operator in dependabot for indirect deps

operator/config/default/kustomization.yaml, operator/config/default/metrics-service.yaml
It already exists, we just need to expose it.
=> operator: expose metrics endpoint as a service

server/config/server/deployment.yaml
We'll need to cut a release next week to roll this out to infra-deployments.
=> update traefik to v3.1.2

ci/toolchain_manager.sh, e2e/Makefile, hack/workspaces_install.sh, server/hack/deploy.sh
Mac does not support --directory but it does support short version -d as well as Fedora
=> Make calls to mktemp compatible with mac

operator/config/metrics/kustomization.yaml, operator/config/metrics/monitor.yaml
ArgoCD gets thrown into an out-of-sync loop when the data field exists on the metrics-reader secret.  This is because the service account controller fills in the data field with all the information a service account secret needs, which conflicts with the empty data that ArgoCD expects.  This data field exists because kustomize's secret generator provides a data field by default, and it appears there isn't a way to disable this.
To resolve this, we need to move away from using the secret generator in our kustomization manifests and instead spell out the secret in our manifests directly.
=> operator: don't generate data field for metrics-reader secret

ci/toolchain_manager.sh
With the merging of public-viewer support in kubesaw, we can now test against the latest version of kubesaw during testing.
Also, with the removal of the target branches, ci is broken.
=> ci: use latest kubesaw during testing

.github/workflows/security.yaml
When running gosec locally with the provided arguments, gosec reports internal panics since the top level of this repo isn't a go module.  To fix these issues, we should run gosec in each component of this repository.
=> run gosec in each component separately

.github/workflows/security.yaml
This reverts commit b8a9d067d79008d8b36fbc1c258350439e4940b4.  It broke CI, and our old config was working, so go back to it.
=> Revert "run gosec in each component separately"

server/api/v1alpha1/workspace_types.go, server/persistence/mapper/internalworkspace_to_workspace_test.go, server/persistence/mutate/owner.go, server/persistence/readclient/readclient_list.go, server/persistence/readclient/readclient_list_test.go, server/persistence/readclient/readclient_read.go, server/persistence/readclient/readclient_read_test.go, server/persistence/writeclient/writeclient_create.go, server/persistence/writeclient/writeclient_create_test.go, server/persistence/writeclient/writeclient_update.go, server/persistence/writeclient/writeclient_update_test.go
When requesting workspaces through our server, we will now label them with the label `internal.workspaces.konflux-ci.dev/is-owner`.  This label will either be set to `true` or `false` depending on whether the requesting user is an owner or not.
This label is set for all operations - get, list, create, and update.
Prerequisite for #293.
=> add is-owner label

server/api/v1alpha1/workspace_types.go, server/persistence/clientinterface/readclient.go, server/persistence/iwclient/iwclient.go, server/persistence/iwclient/iwclient_read.go, server/persistence/iwclient/iwclient_read_test.go, server/persistence/mutate/access.go, server/persistence/readclient/interface_test.go, server/persistence/readclient/mocks/readclient.go, server/persistence/readclient/readclient.go, server/persistence/readclient/readclient_list.go, server/persistence/readclient/readclient_list_test.go, server/persistence/readclient/readclient_read.go, server/persistence/readclient/readclient_read_test.go, server/persistence/writeclient/writeclient_create.go, server/persistence/writeclient/writeclient_create_test.go, server/persistence/writeclient/writeclient_update.go, server/persistence/writeclient/writeclient_update_test.go
When requesting workspaces through our server, we will now label them with the label `internal.workspaces.konflux-ci.dev/is-owner`.  This label will either be set to `true` or `false` depending on whether the requesting user is an owner or not.
This label is set for all operations - get, list, create, and update.
=> add labels indicating access

server/config/server/proxy-config/dynamic/config.yaml
This limits the JWT source in the request to the Authorization header.
=> rest: enforce JWT Bearer token source

e2e/features/restapi/patch.feature, e2e/step/user/user.go, e2e/step/user/user_when.go, server/config/server/proxy-config/dynamic/config.yaml, server/core/workspace/workspace_patch.go, server/core/workspace/workspace_patch_test.go, server/go.mod, server/main.go, server/rest/server.go, server/rest/workspace/patch.go, server/rest/workspace/patch_test.go
=> rest: add initial support for PATCH
